<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="crackvac">
    <!-- materials -->
    <material name="grey">
       <color rgba="0.7 0.7 0.7 1.0"/> 
    </material>
    <material name="blue">
       <color rgba="0 0 0.9 1.0"/> 
    </material>
    <material name="black">
       <color rgba="0 0 0 1.0"/> 
    </material>

    <!-- constants -->
    <xacro:property name="wheel_radius" value="0.04"/> <!-- length unit: m-->
    <xacro:property name="wheel_width" value="0.03"/> 
    <xacro:property name="wheel_base" value="0.4064"/> 
    <xacro:property name="wheel_base_half" value="${wheel_base / 2}"/> 
    <xacro:property name="chassis_depth" value="0.2032"/>
    <xacro:property name="chassis_mass" value="7.0"/> <!-- mass unit: kg-->
    <xacro:property name="wheel_mass" value="0.186"/> <!-- mass unit: kg-->
     
    <!-- macros -->
    <link name="dummy_link">
        <collision>
            <geometry>
                <box size="${wheel_base} ${wheel_base} ${chassis_depth}"/> 
            </geometry>
        </collision>
        <inertial>
            <mass value="${chassis_mass}"/> 
            <inertia 
                ixx="${1/12 * chassis_mass * (wheel_base * wheel_base + chassis_depth * chassis_depth)}"
                ixy="0.0"
                ixz="0.0"
                iyy="${1/12 * chassis_mass * (wheel_base * wheel_base + chassis_depth * chassis_depth)}"
                iyz="0.0"
                izz="${1/12 * chassis_mass * (wheel_base * wheel_base + wheel_base * wheel_base)}"
            />
        </inertial>
    </link>
    <joint name="base_fixedpoint" type="fixed">
       <parent link="base_link"/>
       <child link="dummy_link"/>
    </joint>

    <xacro:macro name="chassis">
        <link name="base_link">
            <visual>
                <geometry>
                    <box size="${wheel_base} ${wheel_base} ${chassis_depth}"/> 
                </geometry> 
                <origin xyz="0.0 0.0 ${chassis_depth / 2}" rpy="0.0 0.0 0.0"/>
                <material name="grey"/>
            </visual>
        </link>    
    </xacro:macro>
    
    <xacro:macro name="swerve_module" params="name mount">
        <link name="${name}_steer_link">
            <visual>
                <geometry>
                    <cylinder radius="0.05" length="0.01"/> 
                </geometry> 
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="blue"/>
            </visual>
        </link>

        <link name="${name}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.57 0 0"/> <!-- 90 degree is 1.57 rad -->
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
            </collision>
            <inertial>
                <mass value="0.079"/>
                <inertia 
                    ixx="${1/12 * wheel_mass* (3 * wheel_radius * wheel_radius + wheel_width * wheel_width)}"
                    ixy="0.0"
                    ixz="0.0"
                    iyy="${1/12 * wheel_mass* (3 * wheel_radius * wheel_radius + wheel_width * wheel_width)}"
                    iyz="0.0"
                    izz="${1/2 * wheel_mass * wheel_radius * wheel_radius}"
                />
            </inertial>
        </link>

        <joint name="${name}_steer_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${name}_steer_link"/>
            <origin xyz="${mount}" rpy="0 0 0"/> 
            <axis xyz="0 0 1"/>
        </joint>
        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="${name}_steer_link"/>
            <child link="${name}_wheel_link"/>
            <origin xyz="0 0 ${-wheel_radius}" rpy="0.0 0.0 0.0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <!-- implementation -->
    <xacro:chassis />
    <xacro:swerve_module name="front_left" mount="-${wheel_base_half} ${wheel_base_half} 0.0"/>    
    <xacro:swerve_module name="front_right" mount="${wheel_base_half} ${wheel_base_half} 0.0"/>    
    <xacro:swerve_module name="back_left" mount="-${wheel_base_half} -${wheel_base_half} 0.0"/>    
    <xacro:swerve_module name="back_right" mount="${wheel_base_half} -${wheel_base_half} 0.0"/>    

    <!-- control -->
    <xacro:include filename="drivetrain_control.xacro"/>
</robot>